<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<UseWPF>true</UseWPF>
		<AssemblyName>VietHoaInstaller</AssemblyName>
		<RootNamespace>VietHoaInstaller</RootNamespace>

		<!-- Nguồn duy nhất khai báo version của app. Mỗi lần release, chỉ cần sửa số này ở đây -->
		<Version>2.0</Version>

		<!-- Đóng gói tối ưu: 1 file .exe duy nhất, không cần cài .NET Runtime -->
		<SelfContained>true</SelfContained>
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>
		<PublishSingleFile>true</PublishSingleFile>
		<PublishReadyToRun>true</PublishReadyToRun>
		<IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
		<DebugType>none</DebugType>
		<SatelliteResourceLanguages>vi</SatelliteResourceLanguages>
		<EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
		<ApplicationIcon>Assets\Dich2000sICON.ico</ApplicationIcon>
	</PropertyGroup>

	<ItemGroup>
		<None Remove="Assets\PlagueIncVH.jpg" />
		<None Remove="Assets\RE2_DX11.png" />
		<None Remove="Assets\Dich2000sICON.ico" />
	</ItemGroup>

	<ItemGroup>
		<Resource Include="Assets\PlagueIncVH.jpg" />
		<Resource Include="Assets\RE2_DX11.png" />
		<Resource Include="Assets\Dich2000sICON.ico" />
	</ItemGroup>

</Project>